version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5005:5001
    depends_on:
      - db
    environment:
      DB_URL: postgresql://your_username:your_password@db:5432/your_database_name

volumes:
  postgres_data:
