FROM python:3.10-slim-bullseye


RUN apt-get update && apt-get -y upgrade && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN pip install poetry

RUN mkdir /src
WORKDIR /src

COPY poetry.lock pyproject.toml /src/
RUN poetry config virtualenvs.create false
RUN poetry install --only main

COPY /src /src

CMD ["poetry", "run", "uvicorn", "src.app:app", "--port", "4011", "--host", "0.0.0.0", "--reload"]
